### ISSUE TITLE
Build instructions / dependencies missing

### ISSUE THREAD

**Issue by eddy-geek** [rhinstaller/blivet-gui#11] opened 2015-04-25 13:24 UTC
I am trying to build blivet-gui on ubuntu (as the ppa is almost empty).

Until now I have tried:

```
sudo apt-get install python-gobject python-gi intltool build-essentials
make
sudo make install
sudo python setup.py install
```

And I currently get (with or without sudo)

```
> blivet-gui
Traceback (most recent call last):
  File "/usr/local/bin/blivet-gui", line 31, in <module>
    from gi.repository import Gtk
ImportError: cannot import name Gtk
```

**Comment by vojtechtrefny** [comment] 2015-04-27 08:48
Hi, check the "blivet-gui.spec" file for the list of dependencies -- the "Requires" lines contains names of Fedora packages blivet-gui depends on.

The problem is there is a lot of packages that are not in Ubuntu repositories: python-blivet, python-meh, python-kickstart, libblockdev...

**Comment by Peque** [comment] 2016-10-20 07:54
Some documentation on how to build/develop would be useful (i.e.: an INSTALL file, or some initial steps in the README file). :blush:

**Comment by osmoc** [comment] 2017-06-13 13:42
Would be even better to have regularly updated ppa - until it's merged to Debian/Ubuntu repositories at least.

**Comment by vojtechtrefny** [comment] 2017-06-13 13:55
> Would be even better to have regularly updated ppa - until it's merged to Debian/Ubuntu repositories at least.

This would definitely be the best, but I'm not a Debian packager and I was never able to finish building blivet-gui in the PPA.

I'll at least try to update the README as soon as possible.

**Comment by vojtechtrefny** [comment] 2017-06-19 13:39
Bad news, I've tried to install blivet-gui manually on Ubuntu to at least provide some howto for "advanced users" and I've found out that blivet actually depends on _hawkey_ -- DNF library that is available only on Fedora (and it can't work on a non-RPM distribution). It is used just to check version of external tools so it shouldn't be so hard to replace this with some solution that is not distribution specific, but right now this means, that it isn't possible to run blivet-gui on Debian/Ubuntu.

Issue for blivet: https://github.com/rhinstaller/blivet/issues/607

**Comment by Peque** [comment] 2017-06-19 15:30
@vojtechtrefny It would still be great to have that howto for Fedora users (i.e.: how to set up the development environment, how to run the tests...). :innocent:

**Comment by osmoc** [comment] 2017-06-20 09:52
Well, if it's just version check and those tools are packaged as .deb already than you can just put explicit version requirements into debian/control file and there will be no need to check for it in runtime: the package manager will do all the work for you during installation.

One of the ways to kickstart would be to convert rpm -> debian/ using smth like https://sourceforge.net/projects/almohazzem/ and than manually edit the result as necessary.

**Comment by vojtechtrefny** [comment] 2017-06-20 12:09
> @vojtechtrefny It would still be great to have that howto for Fedora users (i.e.: how to set up the development environment, how to run the tests...). 😇

Ok, I'll do that.

**Comment by vojtechtrefny** [comment] 2017-06-20 12:11
> Well, if it's just version check and those tools are packaged as .deb already than you can just put explicit version requirements into debian/control file and there will be no need to check for it in runtime: the package manager will do all the work for you during installation

There is a special check in blivet that allows installing it without all dependencies -- e.g. you don't need `ntfsprogs` to install (and use) blivet, you just can't create partition with NTFS format if you don't have support for it -- so blivet itself doesn't depend on on `ntfsprogs`, but if you have it, blivet will allow you to use it.

**Comment by vojtechtrefny** [comment] 2017-06-27 06:39
#74 fixed this

New readme -- https://github.com/rhinstaller/blivet-gui/blob/master/README.md
New documentation for contributors -- https://github.com/rhinstaller/blivet-gui/blob/master/CONTRIBUTING.md

**Closed by vojtechtrefny** 2017-06-27 06:39 UTC
Labels: question
